archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
  - binary: pulumi-resource-openpgp
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/curioswitch/pulumi-openpgp/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-openpgp/
changelog:
  skip: true
release:
  disable: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
